config/routes.rb
Rails.application.routes.draw do
  root 'cms/pages#index'
  namespace :cms do
    root 'pages#index'
    get 'pages/index', as: 'index'
    resources :categories, except: :show
    resources :users, except: :show
    resources :products
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  self.table_name =  "zj_categories"

  has_many :categories, foreign_key: "category_id"
  belongs_to :category
  has_many :products

  validates :name, presence: true
  validates :name, uniqueness: true

  after_destroy :can_not_destroy_parent
  before_update :can_not_belongs_to_children

  def parent_name
    category ? category.name : "顶层分类"
  end
  
  def options
    Category.all.select{ |c| c != self && !self.categories.include?(c) }.map { |c| [c.name, c.id] }
  end

  private
    def can_not_destroy_parent
      raise "不能删除拥有子类的分类" if categories.count > 0
    end
    
    def can_not_belongs_to_children
      raise "不能选择子分类作为自己的分类" if categories.include?(category)
    end
end

app/models/image.rb
class Image < ActiveRecord::Base
  self.table_name = "zj_images"
  mount_uploader :image_path, ImagePathUploader
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  self.table_name = "zj_products"

  belongs_to :category
  has_many :images, dependent: :destroy

  validates :name, :category_id, presence: true

  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: proc { |attributes| attributes[:image_path].blank? }

  def self.search(keyword)
    if keyword
      where("name like ?", "%#{keyword}%")
    else
      all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = "zj_users"
  has_secure_password

  validates :name, presence: true
  validates :password, presence: true, on: :create
  validates :name, uniqueness: true
  validates :name, length: { in: 5..20 }
  validates :password, length: { in: 5..20 }, on: :create
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "格式不正确"  }
  after_destroy :at_least_one_user
  after_destroy :at_least_one_admin

  scope :admins, -> { where(admin: true) }

  def admin?
    admin == true
  end

  private
    def at_least_one_user
      raise "不能删除最后一位用户" if User.count.zero?
    end

    def at_least_one_admin
      raise "系统必须存在一位管理员" if User.admins.count.zero?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cms/categories_controller.rb
class Cms::CategoriesController < CmsController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all.page(params[:page]).per(25)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to cms_categories_url, notice: '新建分类成功'
    else
      flash.now[:error] = @category.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    begin
      @category.update(category_params)
    rescue Exception => e
      flash[:error] = e.message
      render :edit
    else
      if @category.errors.any?
        flash[:error] = @category.errors.full_messages.to_sentence
        render :edit
      else
        redirect_to cms_categories_url, notice: "修改分类成功"
      end
    end
  end

  def destroy
    begin
      @category.destroy
      flash[:notice] = "删除分类成功"
    rescue Exception => e
      flash[:error] = e.message
    end
    redirect_to cms_categories_url
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :category_id)
    end
end

app/controllers/cms/pages_controller.rb
class Cms::PagesController < CmsController

  def index
  end
end

app/controllers/cms/products_controller.rb
class Cms::ProductsController < CmsController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:keyword]
      @products = Product.search(params[:keyword]).page(params[:page]).per(25)
    else
      @products = Product.page(params[:page]).per(25)
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to cms_products_url, notice: '创建产品成功'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to  cms_products_url, notice: '修改产品成功'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to cms_products_url, notice: '删除产品成功'
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :author, :desc, :long_desc, :category_id)
    end
end

app/controllers/cms/users_controller.rb
class Cms::UsersController < CmsController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all.page(params[:page]).per(25)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to cms_users_path, notice: '创建用户成功'
    else
      flash.now[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to cms_users_url, notice: '修改用户成功'
    else
      flash.now[:error] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    begin
      @user.destroy
      flash[:notice] = "删除用户成功"
    rescue Exception => e
      flash[:error] = e.message
    end
    redirect_to cms_users_url
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  layout 'cms'

  def search
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    @title || ENV["COMPANY_NAME"]
  end
end

app/helpers/cms/categories_helper.rb
module Cms::CategoriesHelper
  def select_options_tip
    if @category.options.empty?
      "暂无任何分类"
    else
      "请选择上级分类"
    end
  end
 
end

app/helpers/cms/products_helper.rb
module Cms::ProductsHelper
end

app/helpers/cms/users_helper.rb
module Cms::UsersHelper
end

app/views/cms/categories/_form.html.slim
= form_for [:cms, @category] do |f|
  .form-group
    = f.label :name, "名称"
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :category_id, "上级分类 (不选择则为顶层分类)"
    = f.select :category_id, @category.options, { include_blank: select_options_tip }, class: "form-control"
  br
  .form-group
    = f.submit "确认", class: "btn btn-primary", data: { disable_with: "正在提交，请稍候" }
    = link_to '返回分类列表', cms_categories_path, class: "btn btn-link"

app/views/cms/categories/index.html.slim
h1
  | 分类列表
  = link_to '新建分类', new_cms_category_path, class: "btn btn-primary pull-right"

table.table.table-hover.table-striped.table-condensed
  thead
    tr
      th ID
      th 名称
      th 上级分类
      th 动作

  tbody
    - @categories.each do |category|
      tr
        td = category.id
        td = category.name
        td = category.parent_name
        td
          = link_to '修改', edit_cms_category_path(category), class: "btn btn-info btn-xs"
          | &nbsp;
          = link_to '删除', [:cms, category], data: {:confirm => '确认删除吗？'}, :method => :delete, class: "btn btn-danger btn-xs"
.text-center
  = paginate @categories

app/views/cms/layouts/_header.html.slim
.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to ENV["COMPANY_NAME"], cms_index_path, class: "navbar-brand"
    .navbar-collapse.collapse
      = form_tag cms_products_path, method: :get, class: "navbar-form navbar-left search-form" do
        .form-group
          input.form-control name="keyword" type="text" placeholder="搜索产品"
      ul.nav.navbar-nav.navbar-right
        li
          a UserName
        li
          a href="#"
            | Logout
            | &nbsp;
            i.fa.fa-sign-out

app/views/cms/layouts/_sidebar.html.slim
ul.list-unstyled
  li.item-l1
    = link_to "公司概况", cms_index_path
  li.item-l1
    = link_to "产品管理", cms_products_path
  li.item-l1
    = link_to "分类管理", cms_categories_path
  li.item-l1
    = link_to "用户管理", cms_users_path

app/views/cms/pages/index.html.slim
h1 公司概况

app/views/cms/products/_form.html.slim
= form_for [:cms, @product] do |f|
  .row
    .col-lg-3
      = f.label :name, "名称", class: "control-label"
      = f.text_field :name, class: "form-control"
    .col-lg-3
      = f.label :category_id, "分类", class: "control-label"
      = f.select :category_id, Category.all.map{ |c| [c.name, c.id] }, { prompt: "请选择分类" }, class: "form-control"
    - if Category.count.zero?
      .col-lg-3
        = link_to "新建分类", new_cms_category_path, class: "btn btn-link", style: "padding-top: 28px;"
  br
  .row
    .col-lg-12
      = f.label :desc, "简述", class: "control-label"
      = f.text_area :desc, rows: 5, class: "form-control"
  br
  .row
    .col-lg-12
      = f.label :long_desc, "详细描述", class: "control-label"
      = f.text_area :long_desc, rows: 10, class: "form-control"

  br
  .row
    .col-lg-2
      = f.fields_for :images do |i|
        = i.file_field :image_path

  br
  .form-group
    = f.submit "确认", class: "btn btn-primary", data: { disable_with: "正在提交，请稍候" }
    = link_to '返回分类列表', cms_products_path, class: "btn btn-link"

app/views/cms/products/edit.html.slim
h1 修改产品

== render 'form'

app/views/cms/products/index.html.slim
h1
  | 产品列表
  = link_to '新建产品', new_cms_product_path, class: "btn btn-primary pull-right"

table.table.table-hover.table-striped.table-condensed
  thead
    tr
      th ID
      th 名称
      th 分类
      th 动作

  tbody
    - @products.each do |product|
      tr
        td = product.id
        td = product.name
        td = product.category.name
        td
          = link_to '详细', [:cms, product], class: "btn btn-success btn-xs"
          | &nbsp;
          = link_to '修改', edit_cms_product_path(product), class: "btn btn-info btn-xs"
          | &nbsp;
          = link_to '删除', [:cms, product], data: {:confirm => '确认删除吗？'}, :method => :delete, class: "btn btn-danger btn-xs"
.text-center
  = paginate @products

app/views/cms/products/new.html.slim
h1 新建产品

== render 'form'

app/views/cms/products/show.html.slim
h1 产品详情

app/views/cms/users/_form.html.slim
= form_for [:cms, @user] do |f|
  h4.text-info
    i.fa.fa-check-square-o
    | &nbsp;
    | 基本资料
  .form-group
  .form-group
    = f.label :name, "用户名"
    = f.text_field :name, class: "form-control", placeholder: "至少为5位字符，大小写字母或数字"
  .form-group
    = f.label :email, "邮箱地址"
    = f.text_field :email, class: "form-control", placeholder: "yourname@example.com"
  label 请选择用户角色
  .radio
    label
      = f.radio_button :admin, false
      | 普通用户
    | &nbsp;&nbsp;&nbsp;
    label
      = f.radio_button :admin, true
      | 管理员
  - if action_name == "edit"
    hr
    h4.text-info
      i.fa.fa-check-square-o
      | &nbsp;
      | 若需要更改密码，请输入新密码
  .form-group
    = f.label :password, "密码"
    = f.password_field :password, class: "form-control", placeholder: "至少为5位字符，大小写字母或数字"
  .form-group
    = f.label :password_confirmation, "确认密码"
    = f.password_field :password_confirmation, class: "form-control", placeholder: "请再次输入密码"
  br
  .form-group
    = f.submit "确认", class: "btn btn-primary", data: { disable_with: "正在提交，请稍候" }
    = link_to '返回用户列表', cms_users_path, class: "btn btn-link"

app/views/cms/users/edit.html.slim
h1 修改用户

== render 'form'

app/views/cms/users/index.html.slim
h1
  | 用户列表
  = link_to '新建用户', new_cms_user_path, class: "btn btn-primary pull-right"

table.table.table-hover.table-striped.table-condensed
  thead
    tr
      th ID
      th 用户名
      th 邮箱
      th 角色
      th 动作

  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.name
        td = user.email
        td = user.admin? ? "管理员" : "普通用户"
        td
          = link_to '修改', edit_cms_user_path(user), class: "btn btn-info btn-xs"
          | &nbsp;
          = link_to '删除', [:cms, user], data: {:confirm => '确认删除吗？'}, :method => :delete, class: "btn btn-danger btn-xs"
.text-center
  = paginate @users

app/views/cms/users/new.html.slim
h1 新建用户

== render 'form'

app/views/layouts/application.html.erb
doctype html
html
  head
    title zhongjiang
    = stylesheet_link_tag 'application'  media: 'all' 'data-turbolinks-track' => true
    = javascript_include_tag 'application' 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

  == yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title = title
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application',  media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

  == yield

  = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/cms.html.slim
doctype html
html
  head
    title = title
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application',  media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body#cms-body
    = render 'cms/layouts/header'
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          = render 'cms/layouts/sidebar'
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = flash_messages(:close, :fade)
          == yield

  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = yield :javascript_bottom